/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WargaRouteImport } from './routes/warga'
import { Route as UmkmRouteImport } from './routes/umkm'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WargaIndexRouteImport } from './routes/warga.index'
import { Route as UmkmIndexRouteImport } from './routes/umkm.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WargaWalletRouteImport } from './routes/warga.wallet'
import { Route as WargaScannerRouteImport } from './routes/warga.scanner'
import { Route as WargaProfilRouteImport } from './routes/warga.profil'
import { Route as WargaMarketplaceRouteImport } from './routes/warga.marketplace'
import { Route as WargaLeaderboardRouteImport } from './routes/warga.leaderboard'
import { Route as WargaDropboxRouteImport } from './routes/warga.dropbox'
import { Route as WargaBillsRouteImport } from './routes/warga.bills'
import { Route as WargaAnnouncementsRouteImport } from './routes/warga.announcements'
import { Route as UmkmProfilRouteImport } from './routes/umkm.profil'
import { Route as UmkmOrdersRouteImport } from './routes/umkm.orders'
import { Route as UmkmCatalogRouteImport } from './routes/umkm.catalog'
import { Route as AdminProfilRouteImport } from './routes/admin.profil'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminEduwisataRouteImport } from './routes/admin.eduwisata'
import { Route as AdminDropboxRouteImport } from './routes/admin.dropbox'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const WargaRoute = WargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => rootRouteImport,
} as any)
const UmkmRoute = UmkmRouteImport.update({
  id: '/umkm',
  path: '/umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WargaIndexRoute = WargaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WargaRoute,
} as any)
const UmkmIndexRoute = UmkmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UmkmRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WargaWalletRoute = WargaWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => WargaRoute,
} as any)
const WargaScannerRoute = WargaScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => WargaRoute,
} as any)
const WargaProfilRoute = WargaProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => WargaRoute,
} as any)
const WargaMarketplaceRoute = WargaMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => WargaRoute,
} as any)
const WargaLeaderboardRoute = WargaLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => WargaRoute,
} as any)
const WargaDropboxRoute = WargaDropboxRouteImport.update({
  id: '/dropbox',
  path: '/dropbox',
  getParentRoute: () => WargaRoute,
} as any)
const WargaBillsRoute = WargaBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => WargaRoute,
} as any)
const WargaAnnouncementsRoute = WargaAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => WargaRoute,
} as any)
const UmkmProfilRoute = UmkmProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => UmkmRoute,
} as any)
const UmkmOrdersRoute = UmkmOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => UmkmRoute,
} as any)
const UmkmCatalogRoute = UmkmCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => UmkmRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEduwisataRoute = AdminEduwisataRouteImport.update({
  id: '/eduwisata',
  path: '/eduwisata',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDropboxRoute = AdminDropboxRouteImport.update({
  id: '/dropbox',
  path: '/dropbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/umkm': typeof UmkmRouteWithChildren
  '/warga': typeof WargaRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dropbox': typeof AdminDropboxRoute
  '/admin/eduwisata': typeof AdminEduwisataRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/profil': typeof AdminProfilRoute
  '/umkm/catalog': typeof UmkmCatalogRoute
  '/umkm/orders': typeof UmkmOrdersRoute
  '/umkm/profil': typeof UmkmProfilRoute
  '/warga/announcements': typeof WargaAnnouncementsRoute
  '/warga/bills': typeof WargaBillsRoute
  '/warga/dropbox': typeof WargaDropboxRoute
  '/warga/leaderboard': typeof WargaLeaderboardRoute
  '/warga/marketplace': typeof WargaMarketplaceRoute
  '/warga/profil': typeof WargaProfilRoute
  '/warga/scanner': typeof WargaScannerRoute
  '/warga/wallet': typeof WargaWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/umkm/': typeof UmkmIndexRoute
  '/warga/': typeof WargaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dropbox': typeof AdminDropboxRoute
  '/admin/eduwisata': typeof AdminEduwisataRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/profil': typeof AdminProfilRoute
  '/umkm/catalog': typeof UmkmCatalogRoute
  '/umkm/orders': typeof UmkmOrdersRoute
  '/umkm/profil': typeof UmkmProfilRoute
  '/warga/announcements': typeof WargaAnnouncementsRoute
  '/warga/bills': typeof WargaBillsRoute
  '/warga/dropbox': typeof WargaDropboxRoute
  '/warga/leaderboard': typeof WargaLeaderboardRoute
  '/warga/marketplace': typeof WargaMarketplaceRoute
  '/warga/profil': typeof WargaProfilRoute
  '/warga/scanner': typeof WargaScannerRoute
  '/warga/wallet': typeof WargaWalletRoute
  '/admin': typeof AdminIndexRoute
  '/umkm': typeof UmkmIndexRoute
  '/warga': typeof WargaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/umkm': typeof UmkmRouteWithChildren
  '/warga': typeof WargaRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dropbox': typeof AdminDropboxRoute
  '/admin/eduwisata': typeof AdminEduwisataRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/profil': typeof AdminProfilRoute
  '/umkm/catalog': typeof UmkmCatalogRoute
  '/umkm/orders': typeof UmkmOrdersRoute
  '/umkm/profil': typeof UmkmProfilRoute
  '/warga/announcements': typeof WargaAnnouncementsRoute
  '/warga/bills': typeof WargaBillsRoute
  '/warga/dropbox': typeof WargaDropboxRoute
  '/warga/leaderboard': typeof WargaLeaderboardRoute
  '/warga/marketplace': typeof WargaMarketplaceRoute
  '/warga/profil': typeof WargaProfilRoute
  '/warga/scanner': typeof WargaScannerRoute
  '/warga/wallet': typeof WargaWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/umkm/': typeof UmkmIndexRoute
  '/warga/': typeof WargaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/roles'
    | '/umkm'
    | '/warga'
    | '/admin/announcements'
    | '/admin/dropbox'
    | '/admin/eduwisata'
    | '/admin/feedback'
    | '/admin/profil'
    | '/umkm/catalog'
    | '/umkm/orders'
    | '/umkm/profil'
    | '/warga/announcements'
    | '/warga/bills'
    | '/warga/dropbox'
    | '/warga/leaderboard'
    | '/warga/marketplace'
    | '/warga/profil'
    | '/warga/scanner'
    | '/warga/wallet'
    | '/admin/'
    | '/umkm/'
    | '/warga/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/roles'
    | '/admin/announcements'
    | '/admin/dropbox'
    | '/admin/eduwisata'
    | '/admin/feedback'
    | '/admin/profil'
    | '/umkm/catalog'
    | '/umkm/orders'
    | '/umkm/profil'
    | '/warga/announcements'
    | '/warga/bills'
    | '/warga/dropbox'
    | '/warga/leaderboard'
    | '/warga/marketplace'
    | '/warga/profil'
    | '/warga/scanner'
    | '/warga/wallet'
    | '/admin'
    | '/umkm'
    | '/warga'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/roles'
    | '/umkm'
    | '/warga'
    | '/admin/announcements'
    | '/admin/dropbox'
    | '/admin/eduwisata'
    | '/admin/feedback'
    | '/admin/profil'
    | '/umkm/catalog'
    | '/umkm/orders'
    | '/umkm/profil'
    | '/warga/announcements'
    | '/warga/bills'
    | '/warga/dropbox'
    | '/warga/leaderboard'
    | '/warga/marketplace'
    | '/warga/profil'
    | '/warga/scanner'
    | '/warga/wallet'
    | '/admin/'
    | '/umkm/'
    | '/warga/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  UmkmRoute: typeof UmkmRouteWithChildren
  WargaRoute: typeof WargaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warga': {
      id: '/warga'
      path: '/warga'
      fullPath: '/warga'
      preLoaderRoute: typeof WargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umkm': {
      id: '/umkm'
      path: '/umkm'
      fullPath: '/umkm'
      preLoaderRoute: typeof UmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warga/': {
      id: '/warga/'
      path: '/'
      fullPath: '/warga/'
      preLoaderRoute: typeof WargaIndexRouteImport
      parentRoute: typeof WargaRoute
    }
    '/umkm/': {
      id: '/umkm/'
      path: '/'
      fullPath: '/umkm/'
      preLoaderRoute: typeof UmkmIndexRouteImport
      parentRoute: typeof UmkmRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/warga/wallet': {
      id: '/warga/wallet'
      path: '/wallet'
      fullPath: '/warga/wallet'
      preLoaderRoute: typeof WargaWalletRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/scanner': {
      id: '/warga/scanner'
      path: '/scanner'
      fullPath: '/warga/scanner'
      preLoaderRoute: typeof WargaScannerRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/profil': {
      id: '/warga/profil'
      path: '/profil'
      fullPath: '/warga/profil'
      preLoaderRoute: typeof WargaProfilRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/marketplace': {
      id: '/warga/marketplace'
      path: '/marketplace'
      fullPath: '/warga/marketplace'
      preLoaderRoute: typeof WargaMarketplaceRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/leaderboard': {
      id: '/warga/leaderboard'
      path: '/leaderboard'
      fullPath: '/warga/leaderboard'
      preLoaderRoute: typeof WargaLeaderboardRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/dropbox': {
      id: '/warga/dropbox'
      path: '/dropbox'
      fullPath: '/warga/dropbox'
      preLoaderRoute: typeof WargaDropboxRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/bills': {
      id: '/warga/bills'
      path: '/bills'
      fullPath: '/warga/bills'
      preLoaderRoute: typeof WargaBillsRouteImport
      parentRoute: typeof WargaRoute
    }
    '/warga/announcements': {
      id: '/warga/announcements'
      path: '/announcements'
      fullPath: '/warga/announcements'
      preLoaderRoute: typeof WargaAnnouncementsRouteImport
      parentRoute: typeof WargaRoute
    }
    '/umkm/profil': {
      id: '/umkm/profil'
      path: '/profil'
      fullPath: '/umkm/profil'
      preLoaderRoute: typeof UmkmProfilRouteImport
      parentRoute: typeof UmkmRoute
    }
    '/umkm/orders': {
      id: '/umkm/orders'
      path: '/orders'
      fullPath: '/umkm/orders'
      preLoaderRoute: typeof UmkmOrdersRouteImport
      parentRoute: typeof UmkmRoute
    }
    '/umkm/catalog': {
      id: '/umkm/catalog'
      path: '/catalog'
      fullPath: '/umkm/catalog'
      preLoaderRoute: typeof UmkmCatalogRouteImport
      parentRoute: typeof UmkmRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eduwisata': {
      id: '/admin/eduwisata'
      path: '/eduwisata'
      fullPath: '/admin/eduwisata'
      preLoaderRoute: typeof AdminEduwisataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dropbox': {
      id: '/admin/dropbox'
      path: '/dropbox'
      fullPath: '/admin/dropbox'
      preLoaderRoute: typeof AdminDropboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDropboxRoute: typeof AdminDropboxRoute
  AdminEduwisataRoute: typeof AdminEduwisataRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDropboxRoute: AdminDropboxRoute,
  AdminEduwisataRoute: AdminEduwisataRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UmkmRouteChildren {
  UmkmCatalogRoute: typeof UmkmCatalogRoute
  UmkmOrdersRoute: typeof UmkmOrdersRoute
  UmkmProfilRoute: typeof UmkmProfilRoute
  UmkmIndexRoute: typeof UmkmIndexRoute
}

const UmkmRouteChildren: UmkmRouteChildren = {
  UmkmCatalogRoute: UmkmCatalogRoute,
  UmkmOrdersRoute: UmkmOrdersRoute,
  UmkmProfilRoute: UmkmProfilRoute,
  UmkmIndexRoute: UmkmIndexRoute,
}

const UmkmRouteWithChildren = UmkmRoute._addFileChildren(UmkmRouteChildren)

interface WargaRouteChildren {
  WargaAnnouncementsRoute: typeof WargaAnnouncementsRoute
  WargaBillsRoute: typeof WargaBillsRoute
  WargaDropboxRoute: typeof WargaDropboxRoute
  WargaLeaderboardRoute: typeof WargaLeaderboardRoute
  WargaMarketplaceRoute: typeof WargaMarketplaceRoute
  WargaProfilRoute: typeof WargaProfilRoute
  WargaScannerRoute: typeof WargaScannerRoute
  WargaWalletRoute: typeof WargaWalletRoute
  WargaIndexRoute: typeof WargaIndexRoute
}

const WargaRouteChildren: WargaRouteChildren = {
  WargaAnnouncementsRoute: WargaAnnouncementsRoute,
  WargaBillsRoute: WargaBillsRoute,
  WargaDropboxRoute: WargaDropboxRoute,
  WargaLeaderboardRoute: WargaLeaderboardRoute,
  WargaMarketplaceRoute: WargaMarketplaceRoute,
  WargaProfilRoute: WargaProfilRoute,
  WargaScannerRoute: WargaScannerRoute,
  WargaWalletRoute: WargaWalletRoute,
  WargaIndexRoute: WargaIndexRoute,
}

const WargaRouteWithChildren = WargaRoute._addFileChildren(WargaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  UmkmRoute: UmkmRouteWithChildren,
  WargaRoute: WargaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
